=== Open-Inflation/fixprice_api/tests/__snapshots__/ClassCatalog.products_list.schema.json
{
  "type": "array",
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "items": {
    "type": "object",
    "required": [
      "active",
      "adult",
      "brand",
      "category",
      "forbidden",
      "id",
      "image",
      "images",
      "inStock",
      "isFresh",
      "isHit",
      "isNew",
      "isPromo",
      "isQRMark",
      "isSeason",
      "maxPrice",
      "minPrice",
      "price",
      "sku",
      "specialPrice",
      "title",
      "unit",
      "unitPrice",
      "url",
      "variantCount",
      "variantId"
    ],
    "properties": {
      "active": {
        "type": "boolean"
      },
      "adult": {
        "type": "boolean"
      },
      "badges": {
        "type": "array",
        "items": {}
      },
      "brand": {
        "anyOf": [
          {
            "type": "object",
            "required": [
              "id",
              "title"
            ],
            "properties": {
              "id": {
                "type": "integer"
              },
              "title": {
                "type": "string",
                "j2sEnumRejected": true
              }
            }
          },
          {
            "type": "null"
          }
        ]
      },
      "category": {
        "type": "object",
        "required": [
          "id",
          "parentCategory",
          "title"
        ],
        "properties": {
          "id": {
            "type": "integer"
          },
          "parentCategory": {
            "type": "null"
          },
          "title": {
            "type": "string",
            "j2sEnumRejected": true
          }
        }
      },
      "forbidden": {
        "type": "boolean"
      },
      "id": {
        "type": "integer"
      },
      "image": {
        "type": "integer"
      },
      "images": {
        "type": "array",
        "items": {
          "type": "object",
          "required": [
            "id",
            "src",
            "title"
          ],
          "properties": {
            "id": {
              "type": "integer"
            },
            "src": {
              "type": "string",
              "format": "uri"
            },
            "title": {
              "type": "null"
            }
          }
        }
      },
      "inStock": {
        "type": "integer"
      },
      "isFresh": {
        "type": "boolean"
      },
      "isHit": {
        "type": "boolean"
      },
      "isNew": {
        "type": "boolean"
      },
      "isPromo": {
        "type": "boolean"
      },
      "isQRMark": {
        "type": "boolean"
      },
      "isSeason": {
        "type": "boolean"
      },
      "maxPrice": {
        "type": "string",
        "j2sEnumRejected": true
      },
      "minPrice": {
        "type": "string",
        "j2sEnumRejected": true
      },
      "price": {
        "type": "string",
        "j2sEnumRejected": true
      },
      "resources": {
        "type": "array",
        "items": {
          "type": "object",
          "required": [
            "link",
            "src",
            "videoType"
          ],
          "properties": {
            "link": {
              "type": "null"
            },
            "src": {
              "type": "string",
              "format": "uri"
            },
            "videoType": {
              "type": "null"
            }
          }
        }
      },
      "sku": {
        "type": "string",
        "j2sEnumRejected": true
      },
      "specialPrice": {
        "type": "null"
      },
      "title": {
        "type": "string",
        "j2sEnumRejected": true
      },
      "unit": {
        "type": "null"
      },
      "unitPrice": {
        "type": "string",
        "j2sEnumRejected": true
      },
      "url": {
        "type": "string",
        "j2sEnumRejected": true
      },
      "variantCount": {
        "type": "integer"
      },
      "variantId": {
        "anyOf": [
          {
            "type": "null"
          },
          {
            "type": "integer"
          }
        ]
      }
    }
  }
}

=== Open-Inflation/fixprice_api/tests/__snapshots__/ClassCatalog.products_list.json
[
  {
    "id": 5024806,
    "sku": "5024806",
    "title": "Поднос, O’Kitchen, 25 см",
    "isFresh": false,
    "isNew": false,
    "isPromo": false,
    "adult": false,
    "isSeason": false,
    "isHit": false,
    "isQRMark": false,
    "forbidden": false,
    "active": true,
    "image": 75653822,
    "images": [
      {
        "id": 75653822,
        "title": null,
        "src": "https://img.fix-price.com/insecure/rs:fit:800:800/plain/bit/_marketplace/images/origin/3b/3b4eca4fa055669b05b6f8a85c209682.jpg"
      }
    ],
    "resources": [
      {
        "src": "https://img.fix-price.com/insecure/rs:fit:800:800/plain/bit/_marketplace/images/origin/3b/3b4eca4fa055669b05b6f8a85c209682.jpg",
        "videoType": null,
        "link": null
      }
    ],
    "unit": null,
    "specialPrice": null,
    "price": "279.00",
    "unitPrice": "",
    "minPrice": "279.00",
    "maxPrice": "279.00",
    "variantCount": 1,
    "variantId": null,
    "url": "dlya-doma/p-5024806-podnos-itchen-25-sm",
    "inStock": 18,
    "brand": {
      "id": 20510,
      "title": "O'Kitchen"
    },
    "category": {
      "id": 2064,
      "title": "Для дома",
      "parentCategory": null
    },
    "badges": []
  },
  {
    "id": 5094146,
    "sku": "5094146",
    "title": "Кувшин, O`Kitchen, 1,8 л",
    "isFresh": false,
    "isNew": false,
    "isPromo": false,
    "adult": false,
    "isSeason": false,
    "isHit": false,
    "isQRMark": false,
    "forbidden": false,
    "active": true,
    "image": 75653918,
    "images": [
      {
        "id": 75653918,
        "title": null,
        "src": "https://img.fix-price.com/insecure/rs:fit:800:800/plain/bit/_marketplace/images/origin/37/37c013a72dea6c570c1e8e0db08c60c2.jpg"
      },
      {
        "id": 75653919,
        "title": null,
        "src": "https://img.fix-price.com/insecure/rs:fit:800:800/plain/bit/_marketplace/images/origin/f4/f45d33907f499c1b996761666bcae542.jpg"
      }
    ],
    "resources": [
      {
        "src": "https://img.fix-price.com/insecure/rs:fit:800:800/plain/bit/_marketplace/images/origin/37/37c013a72dea6c570c1e8e0db08c60c2.jpg",
        "videoType": null,
        "link": null
      },
      {
        "src": "https://img.fix-price.com/insecure/rs:fit:800:800/plain/bit/_marketplace/images/origin/f4/f45d33907f499c1b996761666bcae542.jpg",
        "videoType": null,
        "link": null
      }
    ],
    "unit": null,
    "specialPrice": null,
    "price": "399.00",
    "unitPrice": "",
    "minPrice": "399.00",
    "maxPrice": "399.00",
    "variantCount": 1,
    "variantId": null,
    "url": "dlya-doma/p-5094146-kuvshin-itchen-18-l",
    "inStock": 24,
    "brand": {
      "id": 20510,
      "title": "O'Kitchen"
    },
    "category": {
      "id": 2064,
      "title": "Для дома",
      "parentCategory": null
    },
    "badges": []
  },
  {
    "id": 5092648,
    "sku": "5092648",
    "title": "Сито с ручкой, O`Kitchen, 16 см",
    "isFresh": false,
    "isNew": false,
    "isPromo": false,
    "adult": false,
    "isSeason": false,
    "isHit": false,
    "isQRMark": false,
    "forbidden": false,
    "active": true,
    "image": 75656035,
    "images": [
      {
        "id": 75656035,
        "title": null,
        "src": "https://img.fix-price.com/insecure/rs:fit:800:800/plain/bit/_marketplace/images/origin/89/89e0cf8628ef953570c1239adfa0ea8f.jpg"
      }
    ],
    "resources": [
      {
        "src": "https://img.fix-price.com/insecure/rs:fit:800:800/plain/bit/_marketplace/images/origin/89/89e0cf8628ef953570c1239adfa0ea8f.jpg",
        "videoType": null,
        "link": null
      }
    ],
    "unit": null,
    "specialPrice": null,
    "price": "133.00",
    "unitPrice": "",
    "minPrice": "133.00",
    "maxPrice": "133.00",
    "variantCount": 1,
    "variantId": null,
    "url": "dlya-doma/p-5092648-sito-s-ruchkoy-itchen-16-sm",
    "inStock": 23,
    "brand": {
      "id": 20510,
      "title": "O'Kitchen"
    },
    "category": {
      "id": 2064,
      "title": "Для дома",
      "parentCategory": null
    },
    "badges": []
  },
  {
    "id": 5093737,
    "sku": "5093737",
    "title": "Маслёнка с ножом для масла, O'Kitchen, 15х9 см, в ассортименте",
    "isFresh": false,
    "isNew": false,
    "isPromo": false,
    "adult": false,
    "isSeason": false,
    "isHit": false,
    "isQRMark": false,
    "forbidden": false,
    "active": true,
    "image": 75653823,
    "images": [
      {
        "id": 75653823,
        "title": null,
        "src": "https://img.fix-price.com/insecure/rs:fit:800:800/plain/bit/_marketplace/images/origin/0c/0c9db63a493a1167ce5e04582e49c5b4.jpg"
      },
      {
        "id": 75653824,
        "title": null,
        "src": "https://img.fix-price.com/insecure/rs:fit:800:800/plain/bit/_marketplace/images/origin/6c/6c61c5ae45fbf125aeb16e8bc70880c6.jpg"
      },
      {
        "id": 75653825,
        "title": null,
        "src": "https://img.fix-price.com/insecure/rs:fit:800:800/plain/bit/_marketplace/images/origin/4c/4c6859ed93456b1559a5e2c4381843f4.jpg"
      },
      {
        "id": 75653826,
        "title": null,
        "src": "https://img.fix-price.com/insecure/rs:fit:800:800/plain/bit/_marketplace/images/origin/f5/f59a0aea80fb114c932054407778ecf9.jpg"
      }
    ],
    "resources": [
      {
        "src": "https://img.fix-price.com/insecure/rs:fit:800:800/plain/bit/_marketplace/images/origin/0c/0c9db63a493a1167ce5e04582e49c5b4.jpg",
        "videoType": null,
        "link": null
      },
      {
        "src": "https://img.fix-price.com/insecure/rs:fit:800:800/plain/bit/_marketplace/images/origin/6c/6c61c5ae45fbf125aeb16e8bc70880c6.jpg",
        "videoType": null,
        "link": null
      },
      {
        "src": "https://img.fix-price.com/insecure/rs:fit:800:800/plain/bit/_marketplace/images/origin/4c/4c6859ed93456b1559a5e2c4381843f4.jpg",
        "videoType": null,
        "link": null
      },
      {
        "src": "https://img.fix-price.com/insecure/rs:fit:800:800/plain/bit/_marketplace/images/origin/f5/f59a0aea80fb114c932054407778ecf9.jpg",
        "videoType": null,
        "link": null
      }
    ],
    "unit": null,
    "specialPrice": null,
    "price": "349.00",
    "unitPrice": "",
    "minPrice": "349.00",
    "maxPrice": "349.00",
    "variantCount": 6,
    "variantId": null,
    "url": "dlya-doma/p-5093737-maslnka-s-nojom-dlya-masla-itchen-15h9-sm-v-assortimente",
    "inStock": 80,
    "brand": {
      "id": 20510,
      "title": "O'Kitchen"
    },
    "category": {
      "id": 2064,
      "title": "Для дома",
      "parentCategory": null
    },
    "badges": []
  },
  {
    "id": 5036201,
    "sku": "5036201",
    "title": "Корзина для хранения, O`Kitchen, 29,5х22х12,5 см",
    "isFresh": false,
    "isNew": false,
    "isPromo": false,
    "adult": false,
    "isSeason": false,
    "isHit": false,
    "isQRMark": false,
    "forbidden": false,
    "active": true,
    "image": 75653836,
    "images": [
      {
        "id": 75653836,
        "title": null,
        "src": "https://img.fix-price.com/insecure/rs:fit:800:800/plain/bit/_marketplace/images/origin/01/01f44d25d8366080a533b2c4a6dda78a.jpg"
      },
      {
        "id": 75653837,
        "title": null,
        "src": "https://img.fix-price.com/insecure/rs:fit:800:800/plain/bit/_marketplace/images/origin/71/71bca8ca68f46590fc043e21bbd31b19.jpg"
      },
      {
        "id": 75653838,
        "title": null,
        "src": "https://img.fix-price.com/insecure/rs:fit:800:800/plain/bit/_marketplace/images/origin/78/781532480727b64977862c3d27aec50f.jpg"
      },
      {
        "id": 75653839,
        "title": null,
        "src": "https://img.fix-price.com/insecure/rs:fit:800:800/plain/bit/_marketplace/images/origin/e8/e8c62849f102ab791bf11ec356b33f58.jpg"
      }
    ],
    "resources": [
      {
        "src": "https://img.fix-price.com/insecure/rs:fit:800:800/plain/bit/_marketplace/images/origin/01/01f44d25d8366080a533b2c4a6dda78a.jpg",
        "videoType": null,
        "link": null
      },
      {
        "src": "https://img.fix-price.com/insecure/rs:fit:800:800/plain/bit/_marketplace/images/origin/71/71bca8ca68f46590fc043e21bbd31b19.jpg",
        "videoType": null,
        "link": null
      },
      {
        "src": "https://img.fix-price.com/insecure/rs:fit:800:800/plain/bit/_marketplace/images/origin/78/781532480727b64977862c3d27aec50f.jpg",
        "videoType": null,
        "link": null
      },
      {
        "src": "https://img.fix-price.com/insecure/rs:fit:800:800/plain/bit/_marketplace/images/origin/e8/e8c62849f102ab791bf11ec356b33f58.jpg",
        "videoType": null,
        "link": null
      }
    ],
    "unit": null,
    "specialPrice": null,
    "price": "229.00",
    "unitPrice": "",
    "minPrice": "229.00",
    "maxPrice": "229.00",
    "variantCount": 3,
    "variantId": null,
    "url": "dlya-doma/p-5036201-korzina-dlya-hraneniya-itchen-295h22h125-sm",
    "inStock": 36,
    "brand": {
      "id": 20510,
      "title": "O'Kitchen"
    },
    "category": {
      "id": 2064,
      "title": "Для дома",
      "parentCategory": null
    },
    "badges": []
  },
  {
    "id": 5036799,
    "sku": "5036799",
    "title": "Органайзер для холодильника, O’Kitchen, 27х10,5х8 см, в ассортименте",
    "isFresh": false,
    "isNew": false,
    "isPromo": false,
    "adult": false,
    "isSeason": false,
    "isHit": false,
    "isQRMark": false,
    "forbidden": false,
    "active": true,
    "image": 75653912,
    "images": [
      {
        "id": 75653912,
        "title": null,
        "src": "https://img.fix-price.com/insecure/rs:fit:800:800/plain/bit/_marketplace/images/origin/48/48d69c2d11fd57adc86b3aedff71d3fb.jpg"
      },
      {
        "id": 75653913,
        "title": null,
        "src": "https://img.fix-price.com/insecure/rs:fit:800:800/plain/bit/_marketplace/images/origin/75/757f9012c929d4dfc4d4a75a7cc05372.jpg"
      },
      {
        "id": 75653914,
        "title": null,
