=== Open-Inflation/fixprice_api/tests/__snapshots__/ClassAdvertising.home_brands_list.schema.json
{
  "type": "array",
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "items": {
    "type": "object",
    "required": [
      "alias",
      "id",
      "isEmpty",
      "isFavorite",
      "login",
      "src",
      "stm",
      "title",
      "updatedAt",
      "url"
    ],
    "properties": {
      "alias": {
        "type": "string"
      },
      "id": {
        "type": "integer"
      },
      "isEmpty": {
        "type": "boolean"
      },
      "isFavorite": {
        "type": "boolean"
      },
      "login": {
        "anyOf": [
          {
            "type": "string"
          },
          {
            "type": "null"
          }
        ]
      },
      "src": {
        "type": "string",
        "format": "uri"
      },
      "stm": {
        "type": "boolean"
      },
      "title": {
        "type": "string"
      },
      "updatedAt": {
        "anyOf": [
          {
            "type": "string",
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "string",
                "format": "date-time"
              }
            ]
          },
          {
            "type": "null"
          }
        ]
      },
      "url": {
        "anyOf": [
          {
            "type": "string",
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "string",
                "format": "uri"
              }
            ]
          },
          {
            "type": "null"
          }
        ]
      }
    }
  }
}

=== Open-Inflation/fixprice_api/tests/__snapshots__/ClassAdvertising.home_brands_list.json
[
  {
    "id": 10,
    "alias": "",
    "title": "Play The Game",
    "src": "https://img.fix-price.com/_marketplace/brand/18bc0b2c5ba420a64e3918e6c068e7ed.png",
    "isFavorite": true,
    "url": "https://play-the-game.ru/",
    "stm": true,
    "login": "tshashmurina",
    "updatedAt": "2025-02-24 11:30:47",
    "isEmpty": false
  },
  {
    "id": 400,
    "alias": "",
    "title": "Lays",
    "src": "https://img.fix-price.com/_marketplace/brand/e19d68b6acfc6031671b59d11f3671e8.png",
    "isFavorite": true,
    "url": "",
    "stm": false,
    "login": null,
    "updatedAt": null,
    "isEmpty": false
  },
  {
    "id": 423,
    "alias": "",
    "title": "FRUTOBAR",
    "src": "https://img.fix-price.com/_marketplace/brand/9a5cfe4ad61f5b029eb7e8801e77f2ba.png",
    "isFavorite": true,
    "url": "https://fruto-bar.ru/",
    "stm": true,
    "login": "ebukhtoiarov",
    "updatedAt": "2024-03-11 15:12:39",
    "isEmpty": false
  },
  {
    "id": 566,
    "alias": "",
    "title": "Сладонеж",
    "src": "https://img.fix-price.com/_marketplace/brand/4af117462dc1432d9b5c1385531bd369.png",
    "isFavorite": true,
    "url": "",
    "stm": false,
    "login": "vrodina",
    "updatedAt": "2025-02-24 14:19:25",
    "isEmpty": false
  },
  {
    "id": 594,
    "alias": "",
    "title": "Соленья-Варенья",
    "src": "https://img.fix-price.com/_marketplace/brand/727c78a4fcc963e3ee80579fdcf7911d.png",
    "isFavorite": true,
    "url": "https://соленьяваренья.рф/",
    "stm": true,
    "login": "tshashmurina",
    "updatedAt": "2024-12-19 11:02:44",
    "isEmpty": false
  },
  {
    "id": 12588,
    "alias": "",
    "title": "BonHome",
    "src": "https://img.fix-price.com/_marketplace/brand/bb4a1b5dd953337b574f25c50831b58c.png",
    "isFavorite": true,
    "url": "https://bonhome.info/",
    "stm": true,
    "login": "tshashmurina",
    "updatedAt": "2024-12-19 10:53:15",
    "isEmpty": false
  },
  {
    "id": 12589,
    "alias": "",
    "title": "Bella",
    "src": "https://img.fix-price.com/images/origin/origin/2a2daf868e4e0d3b361ff77dd1b0664b.png",
    "isFavorite": true,
    "url": null,
    "stm": false,
    "login": null,
    "updatedAt": null,
    "isEmpty": false
  },
  {
    "id": 12592,
    "alias": "",
    "title": "Colgate",
    "src": "https://img.fix-price.com/images/origin/origin/cb914e33f92ad7fae4cb71c8f40d4b6f.png",
    "isFavorite": true,
    "url": null,
    "stm": false,
    "login": null,
    "updatedAt": null,
    "isEmpty": false
  },
  {
    "id": 12596,
    "alias": "",
    "title": "Losk",
    "src": "https://img.fix-price.com/_marketplace/brand/dea82627a19954d5dba3d93df66d2b23.png",
    "isFavorite": true,
    "url": "",
    "stm": false,
    "login": null,
    "updatedAt": null,
    "isEmpty": false
  },
  {
    "id": 12597,
    "alias": "",
    "title": "Snack",
    "src": "https://img.fix-price.com/_marketplace/brand/113879babedc5bd4b9dc393e177a5597.png",
    "isFavorite": true,
    "url": "",
    "stm": false,
    "login": null,
    "updatedAt": null,
    "isEmpty": false
  },
  {
    "id": 12607,
    "alias": "",
    "title": "Mars",
    "src": "https://img.fix-price.com/images/origin/origin/b835a57be3cc07e29224f01c078980f2.png",
    "isFavorite": true,
    "url": null,
    "stm": false,
    "login": null,
    "updatedAt": null,
    "isEmpty": false
  },
  {
    "id": 12624,
    "alias": "",
    "title": "Bath Republic",
    "src": "https://img.fix-price.com/_marketplace/brand/c12a8cc97ab063b4c3155b042837b2bc.png",
    "isFavorite": true,
    "url": "https://bath-republic.ru/",
    "stm": true,
    "login": "tshashmurina",
    "updatedAt": "2024-12-19 11:06:58",
    "isEmpty": false
  },
  {
    "id": 12625,
    "alias": "",
    "title": "Flarx",
    "src": "https://img.fix-price.com/_marketplace/brand/e0bde11435188e8502d39c7618b7246e.png",
    "isFavorite": true,
    "url": "https://flarx.ru/",
    "stm": true,
    "login": "tshashmurina",
    "updatedAt": "2024-12-19 10:52:52",
    "isEmpty": false
  },
  {
    "id": 12626,
    "alias": "",
    "title": "Heinz",
    "src": "https://img.fix-price.com/images/origin/origin/8d9cf137a5a04f68d80cf550ce001ca9.png",
    "isFavorite": true,
    "url": null,
    "stm": false,
    "login": null,
    "updatedAt": null,
    "isEmpty": false
  },
  {
    "id": 12627,
    "alias": "",
    "title": "Cotte",
    "src": "https://img.fix-price.com/_marketplace/brand/6edf7d8e6a2c06157a6174cf85038db5.png",
    "isFavorite": true,
    "url": "https://cotte.ru/",
    "stm": true,
    "login": null,
    "updatedAt": null,
    "isEmpty": false
  },
  {
    "id": 12628,
    "alias": "",
    "title": "Skittles",
    "src": "https://img.fix-price.com/_marketplace/brand/1e39dc8a665ff974ddd01c0799455773.png",
    "isFavorite": true,
    "url": "",
    "stm": false,
    "login": null,
    "updatedAt": null,
    "isEmpty": false
  },
  {
    "id": 12631,
    "alias": "",
    "title": "Home Time",
    "src": "https://img.fix-price.com/_marketplace/brand/68da3be7e6efb592c8d6df59573b945d.png",
    "isFavorite": true,
    "url": "https://hometime.com.ru/",
    "stm": true,
    "login": "tshashmurina",
    "updatedAt": "2024-12-19 10:59:41",
    "isEmpty": false
  },
  {
    "id": 12632,
    "alias": "",
    "title": "Glam&Glam",
    "src": "https://img.fix-price.com/_marketplace/brand/85cb1dfddaadc42aa468d1ac4c4ce656.png",
    "isFavorite": true,
    "url": "https://glamandglam.com/",
    "stm": true,
    "login": "tshashmurina",
    "updatedAt": "2024-12-18 17:48:57",
    "isEmpty": false
  },
  {
    "id": 12633,
    "alias": "",
    "title": "Orbit",
    "src": "https://img.fix-price.com/images/origin/origin/2334b2ceec2b5ebbb9038fa2b1a45dc6.png",
    "isFavorite": true,
    "url": null,
    "stm": false,
    "login": null,
    "updatedAt": null,
    "isEmpty": false
  },
  {
    "id": 12635,
    "alias": "",
    "title": "Ola!",
    "src": "https://img.fix-price.com/images/origin/origin/cbb961530f0e8d2ab1182d248849c002.png",
    "isFavorite": true,
    "url": null,
    "stm": false,
    "login": null,
    "updatedAt": null,
    "isEmpty": false
  }
]
