=== Open-Inflation/fixprice_api/tests/__snapshots__/ProductService.info.schema.json
{
  "type": "object",
  "required": [
    "_headers",
    "active",
    "adult",
    "bonusCommunicationEnable",
    "brand",
    "category",
    "description",
    "extraDescriptions",
    "forbidden",
    "id",
    "image",
    "images",
    "informers",
    "isCart",
    "isFavorite",
    "isFresh",
    "isHit",
    "isNew",
    "isPromo",
    "isQRMark",
    "isSeason",
    "properties",
    "sku",
    "specialPrice",
    "title",
    "unitPrice",
    "unitType",
    "url",
    "variants",
    "video",
    "videoLink"
  ],
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "properties": {
    "_headers": {
      "type": "object",
      "required": [
        "access-control-allow-credentials",
        "access-control-allow-headers",
        "access-control-allow-methods",
        "access-control-allow-origin",
        "access-control-expose-headers",
        "access-control-max-age",
        "cache-control",
        "content-type",
        "date",
        "is-logged",
        "server",
        "transfer-encoding",
        "vary",
        "x-city",
        "x-language",
        "x-logged"
      ],
      "properties": {
        "access-control-allow-credentials": {
          "type": "string",
          "enum": [
            "true"
          ]
        },
        "access-control-allow-headers": {
          "type": "string",
          "j2sEnumRejected": true
        },
        "access-control-allow-methods": {
          "type": "string",
          "j2sEnumRejected": true
        },
        "access-control-allow-origin": {
          "type": "string",
          "enum": [
            "*"
          ]
        },
        "access-control-expose-headers": {
          "type": "string",
          "j2sEnumRejected": true
        },
        "access-control-max-age": {
          "type": "string",
          "j2sEnumRejected": true
        },
        "cache-control": {
          "type": "string",
          "enum": [
            "public, max-age=3600"
          ]
        },
        "connection": {
          "type": "string",
          "enum": [
            "close"
          ]
        },
        "content-type": {
          "type": "string",
          "j2sEnumRejected": true
        },
        "date": {
          "type": "string",
          "j2sEnumRejected": true
        },
        "is-logged": {
          "type": "string",
          "j2sEnumRejected": true
        },
        "server": {
          "type": "string",
          "enum": [
            "Unit/1.34.2"
          ]
        },
        "transfer-encoding": {
          "type": "string",
          "enum": [
            "chunked"
          ]
        },
        "vary": {
          "type": "string",
          "j2sEnumRejected": true
        },
        "x-city": {
          "type": "string",
          "j2sEnumRejected": true
        },
        "x-language": {
          "type": "string",
          "enum": [
            "ru"
          ]
        },
        "x-logged": {
          "type": "string",
          "j2sEnumRejected": true
        }
      }
    },
    "active": {
      "type": "boolean"
    },
    "adult": {
      "type": "boolean"
    },
    "bonusCommunicationEnable": {
      "type": "boolean"
    },
    "brand": {
      "type": "object",
      "required": [
        "alias",
        "id",
        "isFavorite",
        "isSTM",
        "login",
        "src",
        "title",
        "updated_at",
        "url"
      ],
      "properties": {
        "alias": {
          "type": "string",
          "j2sEnumRejected": true
        },
        "id": {
          "type": "integer"
        },
        "isFavorite": {
          "type": "boolean"
        },
        "isSTM": {
          "type": "boolean"
        },
        "login": {
          "type": "null"
        },
        "src": {
          "type": "string",
          "j2sEnumRejected": true
        },
        "title": {
          "type": "string",
          "j2sEnumRejected": true
        },
        "updated_at": {
          "type": "null"
        },
        "url": {
          "type": "null"
        }
      }
    },
    "category": {
      "type": "integer"
    },
    "description": {
      "type": "string",
      "j2sEnumRejected": true
    },
    "extraDescriptions": {
      "type": "array",
      "items": {
        "type": "object",
        "required": [
          "alias",
          "id",
          "title",
          "value"
        ],
        "properties": {
          "alias": {
            "type": "string",
            "enum": [
              "nutritionalValue",
              "composition",
              "manufacturerAddress",
              "nutritionalValueSeparated"
            ]
          },
          "id": {
            "type": "integer"
          },
          "title": {
            "type": "string",
            "j2sEnumRejected": true
          },
          "value": {
            "anyOf": [
              {
                "type": "string",
                "j2sEnumRejected": true
              },
              {
                "type": "object",
                "required": [
                  "carbohydrates",
                  "description",
                  "energyValue",
                  "fats",
                  "protein"
                ],
                "properties": {
                  "carbohydrates": {
                    "type": "string",
                    "j2sEnumRejected": true
                  },
                  "description": {
                    "type": "string",
                    "j2sEnumRejected": true
                  },
                  "energyValue": {
                    "type": "string",
                    "j2sEnumRejected": true
                  },
                  "fats": {
                    "type": "string",
                    "j2sEnumRejected": true
                  },
                  "protein": {
                    "type": "string",
                    "j2sEnumRejected": true
                  }
                }
              }
            ]
          }
        }
      }
    },
    "forbidden": {
      "type": "boolean"
    },
    "id": {
      "type": "integer"
    },
    "image": {
      "type": "integer"
    },
    "images": {
      "$ref": "#/$defs/Images"
    },
    "informers": {
      "type": "array",
      "items": {
        "type": "object",
        "required": [
          "alias"
        ],
        "properties": {
          "alias": {
            "type": "string",
            "enum": [
              "loyaltyProgram"
            ]
          }
        }
      }
    },
    "isCart": {
      "type": "boolean"
    },
    "isFavorite": {
      "type": "boolean"
    },
    "isFresh": {
      "type": "boolean"
    },
    "isHit": {
      "type": "boolean"
    },
    "isNew": {
      "type": "boolean"
    },
    "isPromo": {
      "type": "boolean"
    },
    "isQRMark": {
      "type": "boolean"
    },
    "isSeason": {
      "type": "boolean"
    },
    "properties": {
      "$ref": "#/$defs/Array1"
    },
    "resources": {
      "$ref": "#/$defs/Resources"
    },
    "sku": {
      "type": "string",
      "j2sEnumRejected": true
    },
    "specialPrice": {
      "type": "null"
    },
    "title": {
      "type": "string",
      "j2sEnumRejected": true
    },
    "unitPrice": {
      "type": "string",
      "j2sEnumRejected": true
    },
    "unitType": {
      "type": "null"
    },
    "url": {
      "type": "string",
      "j2sEnumRejected": true
    },
    "variants": {
      "type": "array",
      "items": {
        "type": "object",
        "required": [
          "barcode",
          "count",
          "dimensions",
          "fixPrice",
          "height",
          "id",
          "image",
          "length",
          "price",
          "properties",
          "title",
          "unitPrice",
          "weight",
          "width"
        ],
        "properties": {
          "barcode": {
            "type": "string",
            "j2sEnumRejected": true
          },
          "count": {
            "type": "integer"
          },
          "dimensions": {
            "type": "object",
            "required": [
              "height",
              "isPackage",
              "length",
              "weight",
              "width"
            ],
            "properties": {
              "height": {
                "type": "integer"
              },
              "isPackage": {
                "type": "boolean"
              },
              "length": {
                "type": "integer"
              },
              "weight": {
                "type": "integer"
              },
              "width": {
                "type": "integer"
              }
            }
          },
          "fixPrice": {
            "type": "string",
            "j2sEnumRejected": true
          },
          "height": {
            "type": "integer"
          },
          "id": {
            "type": "integer"
          },
          "image": {
            "anyOf": [
              {
                "type": "null"
              },
              {
                "type": "integer"
              }
            ]
          },
          "images": {
            "$ref": "#/$defs/Images"
          },
          "length": {
            "type": "integer"
          },
          "price": {
            "type": "string",
            "j2sEnumRejected": true
          },
          "properties": {
            "$ref": "#/$defs/Array1"
          },
          "resources": {
            "$ref": "#/$defs/Resources"
          },
          "title": {
            "type": "string",
            "j2sEnumRejected": true
          },
          "unitPrice": {
            "type": "string",
            "j2sEnumRejected": true
          },
          "weight": {
            "type": "integer"
          },
          "width": {
            "type": "integer"
          }
        }
      }
    },
    "video": {
      "type": "null"
    },
    "videoLink": {
      "type": "null"
    }
  },
  "$defs": {
    "Array1": {
      "type": "array",
      "minItems": 1,
      "items": {
        "type": "object",
        "required": [
          "alias",
          "id",
          "title",
          "value"
        ],
        "minProperties": 1,
        "properties": {
          "alias": {
            "type": "string",
            "enum": [
              "prodCountry",
              "manufacturer",
              "fake",
              "variant"
            ]
          },
          "id": {
            "type": "integer"
          },
          "title": {
            "type": "string",
            "j2sEnumRejected": true
          },
          "value": {
            "type": "string",
            "enum": [
              "Россия",
              "ООО \"ТД \"Алтей\"",
              "Ассортимент",
              "Пломбир"
            ]
          }
        }
      }
    },
    "Images": {
      "type": "array",
      "minItems": 1,
      "items": {
        "type": "object",
        "required": [
          "id",
          "src",
          "title"
        ],
        "minProperties": 1,
        "properties": {
          "id": {
            "type": "integer"
          },
          "src": {
            "type": "string",
            "format": "uri"
          },
          "title": {
            "type": "null"
          }
        }
      }
    },
    "Resources": {
      "type": "array",
      "minItems": 1,
      "items": {
        "type": "object",
        "required": [
          "link",
          "src",
          "videoType"
        ],
        "minProperties": 1,
        "properties": {
          "link": {
            "type": "null"
          },
          "src": {
            "type": "string",
            "format": "uri"
          },
          "videoType": {
            "type": "null"
          }
        }
      }
    }
  }
}

=== Open-Inflation/fixprice_api/tests/__snapshots__/ProductService.info.json
{
  "id": 1912108,
  "title": "Воздушное суфле \"Весенняя серия\", Пухлый Кролик, 150 г",
  "sku": "1912108",
  "category": 2004,
  "isFresh": false,
  "isNew": false,
  "isPromo": false,
  "isSeason": false,
  "isHit": false,
  "isFavorite": false,
  "isCart": false,
  "isQRMark": false,
  "image": 16831843,
  "adult": false,
  "description": "Воздушное суфле \"Весенняя серия\", Пухлый Кролик, со вкусом пломбира имеет нежную текстуру. Разноцветное, фигурное. Масса нетто: 150 г.",
  "video": null,
  "videoLink": null,
  "forbidden": false,
  "active": true,
  "unitType": null,
  "specialPrice": null,
  "images": [
    {
      "id": 16831843,
      "src": "https://img.fix-price.com/insecure/rs:fit:800:800/plain/pim/images/_default_upload_bucket/1912108_1.jpg",
      "title": null
    },
    {
      "id": 16831844,
      "src": "https://img.fix-price.com/insecure/rs:fit:800:800/plain/pim/images/_default_upload_bucket/1912108.jpg",
      "title": null
    }
  ],
  "properties": [
    {
      "id": 12,
      "alias": "prodCountry",
      "value": "Россия",
      "title": "Страна производства"
    },
    {
      "id": 13,
      "alias": "manufacturer",
      "value": "ООО \"ТД \"Алтей\"",
      "title": "Производитель"
    }
  ],
  "extraDescriptions": [
    {
      "id": 0,
      "alias": "nutritionalValue",
      "value": "Пищевая ценность на 100г. Продукта: белки 0г.; жиры 0г.; углеводы 0г. Энергетическая ценность: 0 ккал.",
      "title": "Пищевая ценность"
    },
    {
      "id": 1,
      "alias": "composition",
      "value": "Сахар, патока крахмальная,желатин пищевой,крахмал кукурузный,ароматизатор пломбир, красители синий блестящий, желтый хинолиновый, понсо 4R.",
      "title": "Состав"
    },
    {
      "id": 2,
      "alias": "manufacturerAddress",
      "value": "623733, Свердловская область, Режевской район, село Останино, ул. Центральная, д.10",
      "title": "Адрес производителя"
    },
    {
      "id": 3,
      "alias": "nutritionalValueSeparated",
      "value": {
        "description": "Пищевая ценность на 100г",
        "energyValue": "",
        "protein": "",
        "fats": "",
        "carbohydrates": ""
      },
      "title": "Пищевая ценность с разбивкой по элементам"
    }
  ],
  "resources": [
    {
      "src": "https://img.fix-price.com/insecure/rs:fit:800:800/plain/pim/images/_default_upload_bucket/1912108_1.jpg",
      "videoType": null,
      "link": null
    },
    {
      "src": "https://img.fix-price.com/insecure/rs:fit:800:800/plain/pim/images/_default_upload_bucket/1912108.jpg",
      "videoType": null,
      "link": null
    }
  ],
  "variants": [
    {
      "id": 65185,
      "title": "",
      "width": 60,
      "height": 140,
      "length": 270,
      "weight": 152,
      "barcode": "1912108",
      "resources": [
        {
          "src": "https://img.fix-price.com/insecure/rs:fit:800:800/plain/pim/images/_default_upload_bucket/1912108_1.jpg",
          "videoType": null,
          "link": null
        },
        {
          "src": "https://img.fix-price.com/insecure/rs:fit:800:800/plain/pim/images/_default_upload_bucket/1912108.jpg",
          "videoType": null,
          "link": null
        }
      ],
      "properties": [
        {
          "id": 100,
          "alias": "fake",
          "value": "Ассортимент",
          "title": "Вариант"
        }
      ],
      "count": 12,
      "price": "59.00",
      "dimensions": {
        "width": 60,
        "height": 140,
        "weight": 152,
        "length": 270,
        "isPackage": true
      },
      "image": 16831843,
      "images": [
        {
          "id": 16831843,
          "src": "https://img.fix-price.com/insecure/rs:fit:800:800/plain/pim/images/_default_upload_bucket/1912108_1.jpg",
          "title": null
        }
      ],
      "fixPrice": "59.00",
      "unitPrice": ""
    },
    {
      "id": 65184,
      "title": "",
      "width": 60,
      "height": 140,
      "length": 270,
      "weight": 152,
      "barcode": "4650139150280",
      "resources": [
        {
          "src": "https://img.fix-price.com/insecure/rs:fit:800:800/plain/pim/images/_default_upload_bucket/25b9c9d882e1461afeaafafc89eab494_1.jpg",
          "videoType": null,
          "link": null
        }
      ],
      "properties": [
        {
          "id": 9,
          "alias": "variant",
          "value": "Пломбир",
          "title": "Вариант"
        }
      ],
      "count": 9,
      "price": "59.00",
      "dimensions": {
        "width": 60,
        "height": 140,
        "weight": 152,
        "length": 270,
        "isPackage": true
      },
      "image": 13254619,
      "images": [
        {
          "id": 13254619,
          "src": "https://img.fix-price.com/insecure/rs:fit:800:800/plain/pim/images/_default_upload_bucket/25b9c9d882e1461afeaafafc89eab494_1.jpg",
          "title": null
        }
      ],
      "fixPrice": "59.00",
      "unitPrice": ""
    }
  ],
  "unitPrice": "",
  "url": "produkty-i-napitki/p-1912108-vozdushnoe-sufle-vesennyaya-seriya-puhlyy-krolik-150-g",
  "brand": {
    "id": 373,
    "src": "",
    "url": null,
    "alias": "",
    "login": null,
    "title": "Пухлый Кролик",
    "updated_at": null,
    "isSTM": false,
    "isFavorite": false
  },
  "informers": [
    {
      "alias": "loyaltyProgram"
    }
  ],
  "bonusCommunicationEnable": false,
  "_headers": {
    "x-language": "ru",
    "x-city": "3",
    "is-logged": "",
    "x-logged": "",
    "vary": "X-City, X-Language, X-Pfm, X-Delivery-Type, X-Logged",
    "cache-control": "public, max-age=3600",
    "content-type": "application/json; charset=UTF-8",
    "access-control-allow-origin": "*",
    "access-control-allow-methods": "GET, POST, PUT, DELETE, HEAD, OPTIONS",
    "access-control-allow-headers": "X-Client-Route, X-Access-Token, Content-Type, X-Key, X-Count, Is-Logged, X-Language, X-City, X-Region, X-Country, X-Pfm, X-Mark, X-Delivery-Type, X-Web-Application-Type, X-Open-Id, Cache-Control, Vary, X-Logged, X-TESTCASE",
    "access-control-expose-headers": "X-Key, X-Count, Is-Logged, X-Language, X-City, X-Region, X-Country, X-Pfm, X-Mark, X-Web-Application-Type, X-Open-Id, X-Child, Cache-Control, Vary, X-Logged",
    "access-control-allow-credentials": "true",
    "access-control-max-age": "3600",
    "server": "Unit/1.34.2",
    "date": "Tue, 31 Mar 2026 05:21:55 GMT",
    "connection": "close",
    "transfer-encoding": "chunked"
  }
}
