=== Open-Inflation/fixprice_api/tests/__snapshots__/unstandard_urls.schema.json
{
  "type": "object",
  "required": [
    "https://api.fix-price.com/buyer/v1/banner/suitable?type=1&path=https:%2F%2Ffix-price.com%2Fcatalog",
    "https://api.fix-price.com/buyer/v1/config/ecom.product.special.price.date.show",
    "https://api.fix-price.com/buyer/v1/cookie-config",
    "https://api.fix-price.com/buyer/v2/geo/ip",
    "https://api.fix-price.com/buyer/v2/geo/ip?utm_referrer=https%3a%2f%2ffix-price.com%2f"
  ],
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "properties": {
    "https://api.fix-price.com/buyer/v1/banner/suitable?type=1&path=https:%2F%2Ffix-price.com%2Fcatalog": {
      "$ref": "#/$defs/Object1"
    },
    "https://api.fix-price.com/buyer/v1/config/ecom.product.special.price.date.show": {
      "$ref": "#/$defs/Object1"
    },
    "https://api.fix-price.com/buyer/v1/cookie-config": {
      "$ref": "#/$defs/Object1"
    },
    "https://api.fix-price.com/buyer/v2/geo/ip": {
      "$ref": "#/$defs/Object1"
    },
    "https://api.fix-price.com/buyer/v2/geo/ip?utm_referrer=https%3a%2f%2ffix-price.com%2f": {
      "$ref": "#/$defs/Object1"
    }
  },
  "$defs": {
    "Object1": {
      "type": "object",
      "required": [
        "x-city",
        "x-client-route",
        "x-key",
        "x-language",
        "x-logged"
      ],
      "minProperties": 1,
      "properties": {
        "x-city": {
          "type": "array",
          "minItems": 1,
          "items": {
            "type": "string",
            "j2sEnumRejected": true
          }
        },
        "x-client-route": {
          "type": "array",
          "minItems": 1,
          "items": {
            "type": "string",
            "enum": [
              "/catalog"
            ]
          }
        },
        "x-key": {
          "type": "array",
          "minItems": 1,
          "items": {
            "type": "string",
            "j2sEnumRejected": true
          }
        },
        "x-language": {
          "type": "array",
          "minItems": 1,
          "items": {
            "type": "string",
            "enum": [
              "ru"
            ]
          }
        },
        "x-logged": {
          "type": "array",
          "minItems": 1,
          "items": {
            "type": "string",
            "j2sEnumRejected": true
          }
        }
      }
    }
  }
}

=== Open-Inflation/fixprice_api/tests/__snapshots__/unstandard_urls.json
{
  "https://api.fix-price.com/buyer/v1/config/ecom.product.special.price.date.show": {
    "x-language": [
      "ru"
    ],
    "x-city": [
      "3"
    ],
    "x-key": [
      "RlhJN2tWUFdEa2pDYlcwc2xuYVhMdz09OjpEcEFyYWlVeldvYXh5THhzaVViL0pBPT0=:96db50e2253c8e3d3fd08ce0e1bb07d7"
    ],
    "x-logged": [
      ""
    ],
    "x-client-route": [
      "/catalog"
    ]
  },
  "https://api.fix-price.com/buyer/v1/banner/suitable?type=1&path=https:%2F%2Ffix-price.com%2Fcatalog": {
    "x-language": [
      "ru"
    ],
    "x-city": [
      "3"
    ],
    "x-key": [
      "RlhJN2tWUFdEa2pDYlcwc2xuYVhMdz09OjpEcEFyYWlVeldvYXh5THhzaVViL0pBPT0=:96db50e2253c8e3d3fd08ce0e1bb07d7"
    ],
    "x-logged": [
      ""
    ],
    "x-client-route": [
      "/catalog"
    ]
  },
  "https://api.fix-price.com/buyer/v2/geo/ip": {
    "x-language": [
      "ru"
    ],
    "x-city": [
      "3"
    ],
    "x-key": [
      "RlhJN2tWUFdEa2pDYlcwc2xuYVhMdz09OjpEcEFyYWlVeldvYXh5THhzaVViL0pBPT0=:96db50e2253c8e3d3fd08ce0e1bb07d7"
    ],
    "x-logged": [
      ""
    ],
    "x-client-route": [
      "/catalog"
    ]
  },
  "https://api.fix-price.com/buyer/v1/cookie-config": {
    "x-language": [
      "ru"
    ],
    "x-city": [
      "3"
    ],
    "x-key": [
      "RlhJN2tWUFdEa2pDYlcwc2xuYVhMdz09OjpEcEFyYWlVeldvYXh5THhzaVViL0pBPT0=:96db50e2253c8e3d3fd08ce0e1bb07d7"
    ],
    "x-logged": [
      ""
    ],
    "x-client-route": [
      "/catalog"
    ]
  },
  "https://api.fix-price.com/buyer/v2/geo/ip?utm_referrer=https%3a%2f%2ffix-price.com%2f": {
    "x-language": [
      "ru"
    ],
    "x-city": [
      "3"
    ],
    "x-key": [
      "RlhJN2tWUFdEa2pDYlcwc2xuYVhMdz09OjpEcEFyYWlVeldvYXh5THhzaVViL0pBPT0=:96db50e2253c8e3d3fd08ce0e1bb07d7"
    ],
    "x-logged": [
      ""
    ],
    "x-client-route": [
      "/catalog"
    ]
  }
}
